"""some changes for combo_products

Revision ID: 4100673deb72
Revises: 42c2f446fef9
Create Date: 2024-01-21 04:59:31.462402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4100673deb72'
down_revision: Union[str, None] = '42c2f446fef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combo_products', sa.Column('monthly_fee', sa.Float(), nullable=True))
    op.add_column('combo_products', sa.Column('yearly_fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('combo_products', 'yearly_fee')
    op.drop_column('combo_products', 'monthly_fee')
    # ### end Alembic commands ###
