"""some changes for combo tool

Revision ID: 702323880e69
Revises: 4100673deb72
Create Date: 2024-01-21 16:35:34.084929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702323880e69'
down_revision: Union[str, None] = '4100673deb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combo', sa.Column('monthly_fee', sa.Float(), nullable=True))
    op.add_column('combo', sa.Column('yearly_fee', sa.Float(), nullable=True))
    op.drop_column('combo_products', 'monthly_fee')
    op.drop_column('combo_products', 'yearly_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combo_products', sa.Column('yearly_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('combo_products', sa.Column('monthly_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('combo', 'yearly_fee')
    op.drop_column('combo', 'monthly_fee')
    # ### end Alembic commands ###
